### ISSUE TITLE
Issues with necessary gateway restart

### ISSUE THREAD

**Issue by melsom** [ggravlingen/pytradfri#54] opened 2017-09-03 12:25 UTC
Hello,

As many others are experiencing. When you reach a certain number of bulbs, the gateway needs restarting every 1-2 days. I use IKEA Trådfri with Home Assistant, and feature wise it works great.

Thing is, whenever I reboot the gateway to be able to reach the bulbs, all light groups are switched to off in Home Assistant. Even though they are on. This happens every time.

Home Assistant says it supports local push, which means updates should be pushed automatically. Any way to fix this? Waiting for IKEA to fix their gateway could take some time.. This just started happening when reaching bulb number 20.

**Comment by lwis** [comment] 2017-09-03 12:58
I've always thought the gateway firmware has a memory leak somewhere. Particularly when you're making requests every 15 seconds, this is quite noticeable.

As for the groups, HA will query the gateway, if the gateway reports the group is off, that's all the information we have.

However, if the app (after a restart) is reporting them as on, there may be a bug in the library.

With the switch to observations imminent, I'm hoping this will be more reliable.

**Comment by melsom** [comment] 2017-09-03 17:21
When checking the TRÅDFRI app after reboot, it shows the groups as being on, and those off obviously off. But HA does not seem to be able to pull this information. 

So there might be a bug somewhere. Please let me know if there is anything I can do to help.

**Comment by hanpal** [comment] 2017-09-16 15:01
One strange thing is that reboot (power off/on) worked fine for me for a long time, fully automated. But since the last month it doesn't, only factory reset works. I've automated this also but this required soldering wires to the circuit board. My automation always tries power off/on and then waits a while and checks if it works, if not, factory reset. Factory reset is initiated almost every day. It may be connected to some pytradfri problem as well but each time that connection is lost, it is also lost using the app so it seems that the gateway has been affected at least.

Memory leaks are highly suspected, probably both in RAM and perhaps also some problems with logs written to flash memory, missing or faulty round robin handling.

**Comment by lwis** [comment] 2017-09-16 15:31
Have you tried not running pytradfri for a few days to see if the issue persists?

**Comment by hanpal** [comment] 2017-09-17 12:32
Well, not running pytradfri would most certainly remove the issue but also completely remove the functionality I want. Not interested in using only a controller (remote) or the app, since I have a fully automated lighting system using Tradfri.

**Comment by spektren** [comment] 2017-10-06 16:22
reboot and factory reset can be issued by network. 

REBOOT: 
coap-client -m post -u "Client_identity" -k "**key**" "coaps://192.168.178.71:5684/15011/9030"

!!!RESET!!! (everything like pairing, groups, etc. will be gone): 
coap-client -m post -u "Client_identity" -k "**key**" "coaps://192.168.178.71:5684/15011/9031"

Maybe this would be a handy extension to pytradfri... 
__ 

@hanpal are you using a kind of automated reconfiguration of your GW after a factory reset or do you reconfigure everthing manually?

**Comment by ggravlingen** [comment] 2017-10-07 07:13
@spektren perhaps this could be added as a method to gateway.py? Please feel free to give it a try!

**Comment by spektren** [comment] 2017-10-07 08:38
Thanks for the hint. I'll give it a shot next week. 
Cheers

**Comment by ioangogo** [comment] 2017-10-07 22:09
> Memory leaks are highly suspected, probably both in RAM and perhaps also some problems with logs written to flash memory, missing or faulty round robin handling.

If anyone hasn't contacted them yet? I am tempted to contact ikea support about this, just to see if they are aware or are working on the issue, Has anyone found any more evidence that there it is caused by a memory issue(I do agree that it is a memory leak, but ikea may need convicing).

**Comment by lwis** [comment] 2017-10-08 06:37
Nobody here has contacted them to my knowledge, and until we have a
concrete way to reproduce they may not believe us.

**Comment by jareware** [comment] 2017-10-08 07:00
FWIW, I'm now on my 3rd GW, and I've of course let them know how it keeps failing on both returns. I find it hard to believe they're not aware of the issue, just seems like there's no-one actively working on it.

**Comment by ioangogo** [comment] 2017-10-08 20:10
@lwis Yeah, if we contact them about a suspected problem they may have the tools to debug it, that is if they were the ones doing the development

**Comment by chemicalstorm** [comment] 2017-10-12 18:11
Just wanted to say that I switched to the dev version of Home Assistant which uses resource observation last week and hev not got any issue with the gateway so far (while I needed to cold reboot it every two days before).
You may consider this as a workaround until Ikea properly fixes the issue.

**Comment by jareware** [comment] 2017-10-13 09:00
@chemicalstorm 

> which uses resource observation

Can you elaborate on that?

**Comment by ioangogo** [comment] 2017-10-13 11:27
I think instead of polling the gatway it subscribes to the devices and the
gateway pushes the information to home assistant

**Comment by chemicalstorm** [comment] 2017-10-13 12:21
@jareware as @ioangogo said. I think all the code related to this functionality has been developed and merged in this PR https://github.com/home-assistant/home-assistant/pull/7815

**Comment by ggravlingen** [comment] 2017-10-13 12:42
@chemicalstorm for the pytradfri-lib lib support for observation was added in #20. The PR you referenced is for the Home Assistant-implementation (which is stand-alone from pytradfri.) :)

**Comment by chemicalstorm** [comment] 2017-10-13 12:48
@ggravlingen thanks for the precision. I was only focusing on HA since OP mentioned using it :)
I don't think it is worth polluting this thread anymore so here are some potential workarounds:
- If you use pytradfri directly, you can use whatever version which has https://github.com/ggravlingen/pytradfri/pull/20 merged in.
- If you use Home Assistant, you can use whatever version which has home-assistant/home-assistant#7815 merged in.

**Comment by jareware** [comment] 2017-10-13 13:31
FWIW, I don't use anything besides the official Android/iOS apps, and my GW *still* requires a daily restart to be reliable.

**Comment by ioangogo** [comment] 2017-10-13 16:47
Hmm, that sounds like the IKEA app may be polling then, i wonder why

**Comment by grischard** [comment] 2017-10-26 05:48
Those of you who experience gateway crashes, what's your power supply? Using Ikea's supplied 2A USB power adapter instead of the USB port at the back of my router has solved the issue for me.

**Comment by jareware** [comment] 2017-10-26 08:24
Using the supplied one since day 1, still crashy.

**Comment by hanpal** [comment] 2017-10-26 11:10
> Has anyone hasn't contacted them yet? I am tempted to contact ikea support about this, just to see if they are aware or are working on the issue, Has anyone found any more evidence that there it is caused by a memory issue(I do agree that it is a memory leak, but ikea may need convicing).

I have actually an informal contact in the Trådfri development team. The instabilities are known and there are no known hardware related problems with the gateways. My contact didn't answer when I asked if they have prioritised development of new features (HomeKit/Alexa/Google) over bug correction but this is my impression. The market wants the new features, otherwise I'd expect that the stability problem had been corrected for several month's ago.

**Comment by hanpal** [comment] 2017-10-29 10:12
Is it possible to have an API to pytradfri that determines if the gateway is unresponsive and may need reset/power cycle? I have added some exception handling in my scripts that call pytradfri and by experimenting I  have a method to decide if the gateway is unresponsive. I would prefer if this could be determined in a better way, e.g a call  to gateway_responsive() for monitoring. Maybe a combination of ping (gateway is "active" on the LAN) and some calls to determine that the gateway is unresponsive even though pingable.

**Comment by ggravlingen** [comment] 2017-10-29 10:15
@hanpal please feel free to raise a PR with a suggested method!

**Comment by hanpal** [comment] 2017-10-29 13:05
I've learned that if I call api_factory, an exception is raised when the gateway is unavailable:

try:
    api = api_factory(ip, key)
except:
    print ("### Trådfri: No contact with the gateway")
    sys.exit(1)

There are som other cases also, it happens that api_factory passes without exception but there are no devices:

try:
    lights = [dev for dev in devices if dev.has_light_control]
except:
    print(" ### Trådfri: No devices")
    sys.exit(2)

**Comment by ggravlingen** [comment] 2017-10-29 13:27
@hanpal I guess something that mimics this would then need to be added to the GatewayInfo-class (https://github.com/ggravlingen/pytradfri/blob/master/pytradfri/gateway.py). Perhaps as a is_available()-method?

**Comment by hanpal** [comment] 2017-10-29 14:28
Yes, would be nice to have, at least for the first case.

The other case with no devices is not obvious how to handle. Why an exception in this case? There might be OK cases where there are no devices with has_light:control. The average user should not have to consider exception handling unless this is documented as a prerequisite for using the method.

**Comment by ggravlingen** [comment] 2017-10-29 14:36
@hanpal :+1: Please feel free to implement the code and then submit a pull request for the main branch.

**Comment by hanpal** [comment] 2017-10-29 15:10
Unfortunately I'm at beginner level regarding python so I don't think this would be a great idea...

**Comment by ggravlingen** [comment] 2017-11-05 18:13
Are people still having troubles with instability on the new firmware version or can this issue be closed now?

**Comment by melsom** [comment] 2017-11-05 18:31
Haven't had any issues yet. Just been a few days though. Hopefully the fixes IKEA has implemented has resolved this issue!

**Comment by migromao** [comment] 2017-11-05 18:57
Working like a charm after new built . Tradfri working without key stored

**Comment by jareware** [comment] 2017-11-06 09:01
Also seeing a dramatic improvement in reliability 👍

**Comment by ggravlingen** [comment] 2017-11-06 09:38
Anecdotal evidence suggests stability has increased. Closing issue.

**Closed by ggravlingen** 2017-11-06 09:38 UTC
Labels: Discussion
